"""Configuration for the isolated multi-agent pure-LLM guidance sandbox."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
WORKSPACE_ROOT = PROJECT_ROOT.parent
DATA_ROOT = WORKSPACE_ROOT.parent

# Pure-LLM artifacts stay inside the new folder only.
RUN_NAME = "isolated_multi_agent_llm"
MODEL_NAME = "isolated_multi_agent_llm"
LOG_DIR = PROJECT_ROOT / "log" / RUN_NAME

EVAL_RUN_NAME = "isolated_multi_agent_llm_eval"
PLOT_DIR = PROJECT_ROOT / "outputs"
EVAL_OUTPUT_DIR = PLOT_DIR / EVAL_RUN_NAME
EVAL_DIR = PROJECT_ROOT / "evaluation"
MEMORY_DIR = PROJECT_ROOT / "memory"
JSON_ANSWERS_DIR = MEMORY_DIR / "json_answers"
EVAL_MEMORY_PATH = MEMORY_DIR / "eval_memory.json"

# Shared data still lives one level above the workspace root.
ROUTES_CSV = DATA_ROOT / "22feb_paths.csv"
WAYPOINTS_CSV = DATA_ROOT / "path_Waypoints22feb.csv"
SECTOR_GEOJSON = DATA_ROOT / "test.geojson"

# Environment defaults.
ROUTE_MIRROR_SUFFIX = "_REV"
MAX_AGENTS = 12
NUM_AGENTS_DEFAULT = 2
ROUTE_IDS_DEFAULT = None
SEED = 42
SAFE_R = 5.0
TRAFFIC_CAUTION_R = 6.5
LAUNCH_SEPARATION_R = TRAFFIC_CAUTION_R
GOAL_RADIUS = 5.0
AGENT_SPEED = 2.0
MAX_STEP = 60
ACTION_BINS = (-30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30)

# Hazard detection and recovery defaults.
HAZARD_LOOKAHEAD_STEPS = 12
EMERGENCY_LOOKAHEAD_STEPS = 5
TURN_PREVIEW_STEPS = 10
PREVIEW_TOP_K = 6
PAIR_RISK_BUFFER = 1.20
WEATHER_CLEARANCE_BUFFER_NM = 2.0
BOUNDARY_WARNING_DISTANCE_UNITS = 2.0
CLEAR_STREAK_REQUIRED = 2
ROUTE_RECOVERY_XTRACK_UNITS = 2.5
DESTINATION_ALIGNMENT_DEG = 8.0
MERGE_BACK_REPEAT_ERROR_DEG = 30.0
MERGE_BACK_RECHECK_STEPS = 2

# Weather defaults.
WEATHER_MAJOR_RADIUS_NM_MIN = 2.5
WEATHER_MAJOR_RADIUS_NM_MAX = 25.0
WEATHER_MINOR_RATIO_MIN = 0.60
WEATHER_MINOR_RATIO_MAX = 0.65
WEATHER_SPEED_NM_PER_STEP_MIN = 0.5
WEATHER_SPEED_NM_PER_STEP_MAX = 1.1666666667
WEATHER_GROWTH_NM_PER_STEP_MIN = 0.15
WEATHER_GROWTH_NM_PER_STEP_MAX = 0.60
WEATHER_TRAIL_STEPS = 5
WEATHER_INIT_TRIES = 300
NUM_WEATHER_CELLS_DEFAULT = 1

# Pure-LLM defaults.
RUN_MODES = ("LLM_ONLY",)
FRAME_DURATION_MS = 250
USE_VISION_DEFAULT = False

# LLM defaults.
# OLLAMA_MODEL = "llama4:latest"
OLLAMA_MODEL = "gemma3:12b"
OLLAMA_TEMPERATURE = 0
OLLAMA_TOP_P = 0.95
OLLAMA_MAX_TOKENS = 1000000
OLLAMA_HOST = "http://127.0.0.1:11434"
OLLAMA_TIMEOUT_SECONDS = 120
